# Single node single drive Minio
# https://min.io/docs/minio/container/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html
#  http://127.0.0.1:39001
services:
  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    command: server /data --console-address :9001
    healthcheck:
      test: mc ready local
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "dorm_system"