"""add tickets table

Revision ID: 147dd539ce68
Revises: b2fbd56976d2
Create Date: 2025-12-07 19:05:55.550160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147dd539ce68'
down_revision: Union[str, Sequence[str], None] = 'b2fbd56976d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('repair', 'maintenance', 'receipt', 'large_item', name='ticket_type'), nullable=False),
    sa.Column('status', sa.Enum('in_processing', 'in_work', 'done', name='ticket_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_created_at'), 'ticket', ['created_at'], unique=False)
    op.create_table('ticket_attachment',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_storage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_attachment_created_at'), 'ticket_attachment', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_attachment_created_at'), table_name='ticket_attachment')
    op.drop_table('ticket_attachment')
    op.drop_index(op.f('ix_ticket_created_at'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
