"""modify ticket table

Revision ID: 59d993a83042
Revises: 147dd539ce68
Create Date: 2025-12-08 20:13:45.246595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d993a83042'
down_revision: Union[str, Sequence[str], None] = '147dd539ce68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('admin_comment', sa.Text(), nullable=True))
    op.add_column('ticket', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'closed_at')
    op.drop_column('ticket', 'admin_comment')
    # ### end Alembic commands ###
