"""guest_pass

Revision ID: 3af6b3b4c99d
Revises: bf35d7032730
Create Date: 2026-02-02 22:36:11.469057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af6b3b4c99d'
down_revision: Union[str, Sequence[str], None] = 'bf35d7032730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_pass',
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('guest_full_name', sa.Text(), nullable=False),
    sa.Column('guest_document', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('planned_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'checked_in', 'checked_out', 'expired', name='guest_pass_status'), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('code', name='uq_guest_pass_code')
    )
    op.create_index(op.f('ix_guest_pass_created_at'), 'guest_pass', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_pass_created_at'), table_name='guest_pass')
    op.drop_table('guest_pass')
    # ### end Alembic commands ###
